os: linux

language: python

python:
  - "3.6"

services:
  - docker

git:
  depth: 1

addons:
  apt:
    update: true
    packages:
      - docker-ce

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master

stages:
  - name: lint
  - name: test

env:
  global:
    - LATEST_RELEASE=12-alpine
    - DOCKER_REPO=tecnativa/postgres-autoconf
  jobs:
    - DOCKER_TAG=9.6-alpine
    - DOCKER_TAG=10-alpine
    - DOCKER_TAG=11-alpine
    - DOCKER_TAG=12-alpine

jobs:
  include:
    stage: lint
    script:
      - pre-commit run --all --show-diff-on-failure

install:
  - pip install -r tests/ci-requirements.txt

script:
  - ./tests/test.py -v

deploy:
  provider: script
  script: ./hooks/push
  on:
    branch: master
