#!/usr/bin/env bash
set -ex

# Check environment variables are present
test -n "$DOCKER_TAG"

# Prepare build args
commit="${GIT_SHA1:-$TRAVIS_COMMIT}"

# To be configured via Docker Hub UI, all labels from postgres image targeting
# this master branch
time docker image build \
    --build-arg VCS_REF="$commit" \
    --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
    --build-arg BASE_TAG="$DOCKER_TAG" \
    --tag "tecnativa/postgres-autoconf:$DOCKER_TAG" \
    .
