#!/usr/bin/env python3
from plumbum import FG, local
from plumbum.cmd import docker

REGISTRY = local.env.get("REGISTRY_HOST", "docker.io")
REPO = local.env["DOCKER_REPO"]
SUFFIX = local.env.get("DOCKER_REPO_SUFFIX", "")
VERSION = local.env["DOCKER_TAG"]

# Log all locally available images; will help to pin images
docker["image", "ls", "--digests", REPO] & FG

# Login in Docker Hub
docker(
    "login",
    "--username",
    local.env["REGISTRY_USERNAME"],
    "--password",
    local.env["REGISTRY_TOKEN"],
    REGISTRY,
)

# Push built images
local_image = "%s:%s" % (REPO, VERSION)
public_image = "%s/%s%s:%s" % (REGISTRY, REPO, SUFFIX, VERSION)
docker["image", "tag", local_image, public_image]
docker["image", "push", public_image] & FG
if VERSION == local.env.get("LATEST_RELEASE"):
    latest_version = "alpine" if VERSION.endswith("-alpine") else "latest"
    public_image = "%s/%s%s:%s" % (REGISTRY, REPO, SUFFIX, latest_version)
    docker["image", "tag", local_image, public_image] & FG
    docker["image", "push", public_image] & FG
